import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Country of the day',
    template: '%s - Country of the day',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
