import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import '../globals.css';

type LocaleLayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

export const metadata: Metadata = {
  title: {
    default: 'Country of the day',
    template: '%s - Country of the day',
  },
  description: 'Generated by create next app',
};

export default function LocaleLayout({ children, params }: LocaleLayoutProps) {
  return (
    <html lang={params.locale} className={GeistSans.className}>
      <body>{children}</body>
    </html>
  );
}
